# --setting=portfolio.local_settings
run:
	python manage.py runserver 
run3:
	python manage.py runserver 3000

run5:
	python manage.py runserver 5000

run7:
	python manage.py runserver 7000

makemigrations:
	python manage.py makemigrations

migrate:
	python manage.py migrate
