# Generated by Django 5.2.4 on 2025-10-12 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_qrcode_link_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="link",
            options={"ordering": ("-updated_at",)},
        ),
    ]
